### ISSUE TITLE
Error when selecting locale

### ISSUE THREAD

**Issue by blizarazu** [Roman-Lo/vscode-ng-i18n-editor#7]
Hi,
I'm trying to use the extension in a project where the locales are merged using xliffmerge and every time I choose the xlf file and the locale I get this error:
```
Command Execution Failed
Failed to execute: 'xliff-file-loaded', error: the translation file target locale is not match. actual: null, expected: en [0]. Hash: 1595318910453.
```
My `.ngI18nconfig` file looks like this:
```
{
  "locales": [
    "es",
    "en"
  ],
  "editor": {
    "messageLocations": [
      "src/locale/messages.xlf"
    ],
    "mode": "target-file",
    "translationFileNamePattern": "${name}.${lang}"
  }
}
```
The src/locale directory contains these files:
messages.xlf
messages.en.xlf
messages.es.xlf

Thank you

**Comment by blizarazu** [comment]
Thank you for the help. I was using version 2 of xliff. I switched to version 1.2 and everything is working fine now.

**Comment by eluchsinger** [comment]
@Roman-Lo apparently XLIFF 2.0 does not work. Or do you have a template that works?

I always get the same error when I try to read a 2.0 file. Even when I import the one from [Wikipedia](https://en.wikipedia.org/wiki/XLIFF#XLIFF_2.0_and_higher_(the_current_OASIS_ratified_format)).
